# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '**/BreathRateRecognition.csproj'
    arguments: ' --configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/package/BreathRateRecognition-dotnetcore31.zip'
    zipAfterPublish: true
    publishWebProjects: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '**/BreathRateRecognition.csproj'
    arguments: ' --configuration $(buildConfiguration) -r win-x64 --self-contained true --output $(build.artifactstagingdirectory)/win-x64/BreathRateRecognition-win-x64.zip'
    zipAfterPublish: true
    publishWebProjects: true
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '**/BreathRateRecognition.csproj'
    arguments: ' --configuration $(buildConfiguration) -r win-x86 --self-contained true --output $(build.artifactstagingdirectory)/win-x86/BreathRateRecognition-win-x86.zip'
    zipAfterPublish: true
    publishWebProjects: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '**/BreathRateRecognition.csproj'
    arguments: ' --configuration $(buildConfiguration) -r linux-x64 --self-contained true --output $(build.artifactstagingdirectory)/linux-x64/BreathRateRecognition-linux-x64.zip'
    zipAfterPublish: true
    publishWebProjects: true


- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '**/BreathRateRecognition.csproj'
    arguments: ' --configuration $(buildConfiguration) -r linux-arm --self-contained true --output $(build.artifactstagingdirectory)/linux-arm/BreathRateRecognition-linux-arm.zip'
    zipAfterPublish: true
    publishWebProjects: true


- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(build.artifactstagingdirectory)/package/BreathRateRecognition-dotnetcore31.zip'
    artifact: 'package'
    publishLocation: 'pipeline'

- task: PublishPipelineArtifact@1
  inputs:
   targetPath: '$(build.artifactstagingdirectory)/win-x64/BreathRateRecognition-win-x64.zip'
   artifact: 'win-x64'
   publishLocation: 'pipeline'
- task: PublishPipelineArtifact@1
  inputs:
   targetPath: '$(build.artifactstagingdirectory)/win-x86/BreathRateRecognition-win-x86.zip'
   artifact: 'win-x86'
   publishLocation: 'pipeline'
- task: PublishPipelineArtifact@1
  inputs:
   targetPath: '$(build.artifactstagingdirectory)/linux-x64/BreathRateRecognition-linux-x64.zip'
   artifact: 'linux-x64'
   publishLocation: 'pipeline'
- task: PublishPipelineArtifact@1
  inputs:
   targetPath: '$(build.artifactstagingdirectory)/linux-arm/BreathRateRecognition-linux-arm.zip'
   artifact: 'linux-arm'
   publishLocation: 'pipeline'
    