# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '**/BreathRateRecognition.csproj'
    arguments: ' --configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/dotnetcore31'
    publishWebProjects: true

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.artifactstagingdirectory)/dotnetcore31'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/package/brr-dotnetcore31.zip'
    replaceExistingArchive: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '**/BreathRateRecognition.csproj'
    arguments: ' --configuration $(buildConfiguration) -r win-x64 --self-contained true --output $(build.artifactstagingdirectory)/win-x64'
    publishWebProjects: true
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.artifactstagingdirectory)/win-x64'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/package/brr-win-x64.zip'
    replaceExistingArchive: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '**/BreathRateRecognition.csproj'
    arguments: ' --configuration $(buildConfiguration) -r win-x86 --self-contained true --output $(build.artifactstagingdirectory)/win-x86/BreathRateRecognition-win-x86.zip'
    publishWebProjects: true

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.artifactstagingdirectory)/win-x86'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/package/brr_win-x86.zip'
    replaceExistingArchive: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '**/BreathRateRecognition.csproj'
    arguments: ' --configuration $(buildConfiguration) -r linux-x64 --self-contained true --output $(build.artifactstagingdirectory)/linux-x64'
    publishWebProjects: true

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.artifactstagingdirectory)/linux-x64'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/package/brr-linux-x64.zip'
    replaceExistingArchive: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '**/BreathRateRecognition.csproj'
    arguments: ' --configuration $(buildConfiguration) -r linux-arm --self-contained true --output $(build.artifactstagingdirectory)/linux-arm'
    publishWebProjects: true

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.artifactstagingdirectory)/linux-arm'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/package/brr-linux-arm.zip'
    replaceExistingArchive: true

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(build.artifactstagingdirectory)/package'
    artifact: 'package'
    publishLocation: 'pipeline'
    